apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-students
  namespace: wep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-students
  template:
    metadata:
      labels:
        app: db-students
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: wep-students
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U postgres
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: pgdata
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db-students-service
  namespace: wep
spec:
  selector:
    app: db-students
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
