apiVersion: v1
kind: ConfigMap
metadata:
  name: wep-config
  namespace: wep
data:
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/wep"
  MS_AUTHENTICATION_SERVICE: "http://ms.authentication-service:3002"
  MS_STUDENTS_SERVICE: "http://ms.students-service:3001"
  MS_TEACHERS_SERVICE: "http://ms.teachers-service:3004"
  MS_NOTIFICATIONS_SERVICE: "http://ms.notifications-service:3003"
  MS_COURSES_SERVICE: "http://ms.courses-service:3005"
  MS_CLASSES_SERVICE: "http://ms.classes-service:3006"
  MS_SCHEDULE_SERVICE: "http://ms.schedule-service:3007"
  MS_ATTENDANCE_SERVICE: "http://ms.attendance-service:3008"
  MS_MESSAGING_SERVICE: "http://ms.messaging-service:3009"
  MS_NOTES_SERVICE: "http://ms.notes-service:3010"