apiVersion: v1
kind: ConfigMap
metadata:
  name: wep-config
  namespace: wep
data:
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/wep"
  DB_AUTH_URL: "postgresql://postgres:postgres@db-auth-service:5432/wep-auth"
  DB_STUDENTS_URL: "postgresql://postgres:postgres@db-students-service:5432/wep-students"
  DB_TEACHERS_URL: "postgresql://postgres:postgres@db-teachers-service:5432/wep-teachers"
  DB_COURSES_URL: "postgresql://postgres:postgres@db-courses-service:5432/wep-courses"
  DB_CLASSES_URL: "postgresql://postgres:postgres@db-classes-service:5432/wep-classes"
  DB_SCHEDULE_URL: "postgresql://postgres:postgres@db-schedule-service:5432/wep-schedule"
  DB_ATTENDANCE_URL: "postgresql://postgres:postgres@db-attendance-service:5432/wep-attendance"
  DB_MESSAGING_URL: "postgresql://postgres:postgres@db-messaging-service:5432/wep-messaging"
  DB_GRADES_URL: "postgresql://postgres:postgres@db-grades-service:5432/wep-grades"
  DB_NOTIFICATIONS_URL: "postgresql://postgres:postgres@db-notifications-service:5432/wep-notifications"
  MS_AUTH_SERVICE: "http://ms-auth-service:3002"
  MS_STUDENTS_SERVICE: "http://ms-students-service:3001"
  MS_TEACHERS_SERVICE: "http://ms-teachers-service:3004"
  MS_NOTIFICATIONS_SERVICE: "http://ms-notifications-service:3003"
  MS_COURSES_SERVICE: "http://ms-courses-service:3005"
  MS_CLASSES_SERVICE: "http://ms-classes-service:3006"
  MS_SCHEDULE_SERVICE: "http://ms-schedule-service:3007"
  MS_ATTENDANCE_SERVICE: "http://ms-attendance-service:3008"
  MS_MESSAGING_SERVICE: "http://ms-messaging-service:3009"
  MS_GRADES_SERVICE: "http://ms-grades-service:3010"
