apiVersion: v1
kind: ConfigMap
metadata:
  name: wep-config
  namespace: wep
data:
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/wep"
  DB_AUTH_URL: "postgresql://postgres:postgres@postgres-service:5432/wep_auth"
  DB_STUDENTS_URL: "postgresql://postgres:postgres@postgres-service:5432/wep_students"
  DB_TEACHERS_URL: "postgresql://postgres:postgres@postgres-service:5432/wep_teachers"
  DB_COURSES_URL: "postgresql://postgres:postgres@postgres-service:5432/wep_courses"
  DB_CLASSES_URL: "postgresql://postgres:postgres@postgres-service:5432/wep_classes"
  DB_SCHEDULE_URL: "postgresql://postgres:postgres@postgres-service:5432/wep_schedule"
  DB_ATTENDANCE_URL: "postgresql://postgres:postgres@postgres-service:5432/wep_attendance"
  DB_MESSAGING_URL: "postgresql://postgres:postgres@postgres-service:5432/wep_messaging"
  DB_GRADES_URL: "postgresql://postgres:postgres@postgres-service:5432/wep_grades"
  DB_NOTIFICATIONS_URL: "postgresql://postgres:postgres@postgres-service:5432/wep_notifications"
  MS_AUTH_SERVICE: "http://ms-auth-service:3002"
  MS_STUDENTS_SERVICE: "http://ms-students-service:3001"
  MS_TEACHERS_SERVICE: "http://ms-teachers-service:3004"
  MS_NOTIFICATIONS_SERVICE: "http://ms-notifications-service:3003"
  MS_COURSES_SERVICE: "http://ms-courses-service:3005"
  MS_CLASSES_SERVICE: "http://ms-classes-service:3006"
  MS_SCHEDULE_SERVICE: "http://ms-schedule-service:3007"
  MS_ATTENDANCE_SERVICE: "http://ms-attendance-service:3008"
  MS_MESSAGING_SERVICE: "http://ms-messaging-service:3009"
  MS_GRADES_SERVICE: "http://ms-grades-service:3010"
  MS_DOCS_SERVICE: "http://ms-docs-service:3011"
  KRAKEND_SERVICE: "http://krakend-service:8080"
  SENTRY_DSN: "http://1f46c847e5104623865b17f7830655fa@glitchtip:8000/1"
  SENTRY_ENVIRONMENT: "development"
  SENTRY_TRACES_SAMPLE_RATE: "0.1"
